version: '3.4'
services:
  web:
    build: .
    container_name: demo-page
    volumes:
      - .:/home/webuser
    ports:
      - '1235:1235'
    command: npm run demo
  e2e:
    build: ./puppeteer
    container_name: puppeteer
    volumes:
      - ./scripts:/home/pptruser/scripts
      - ./puppeteer:/home/pptruser
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - web
    environment:
      - DISPLAY
      - DEMO_URL= http://web:1235/demo
    env_file:
      - .env
    command: scripts/wait-for-it.sh web:1235/demo -- npm run test:e2e
