# This is a basic workflow to help you get started with Actions

name: Puppeteer tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          USER_A: ${{ secrets.USER_A }}
          USER_B: ${{ secrets.USER_B }}
          PASSWORD_A: ${{ secrets.PASSWORD_A }}
          PASSWORD_B: ${{ secrets.PASSWORD_B }}
          NUMBER_A: ${{ secrets.NUMBER_A }}
          NUMBER_B: ${{ secrets.NUMBER_B }}
          WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
          REALM: ${{ secrets.REALM }}
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit e2e
          docker cp $(docker-compose ps -q e2e):/home/pptruser/pictures ./puppeteer/screenshots
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./puppeteer/screenshots
          if-no-files-found: error
