# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Populate with environment variables
        run: |
          touch .env
          echo export USER_A="${{secrets.USER_A}}" >> .env
          echo export USER_B="${{secrets.USER_B}}" >> .env
          echo export PASSWORD_A="${{secrets.PASSWORD_A}}" >> .env
          echo export PASSWORD_B="${{secrets.PASSWORD_B}}" >> .env
          echo export NUMBER_A="${{secrets.NUMBER_A}}" >> .env
          echo export NUMBER_B="${{secrets.NUMBER_B}}" >> .env
          echo export WEBSOCKET_URL="${{secrets.WEBSOCKET_URL}}" >> .env
          echo export REALM="${{secrets.REALM}}" >> .env
      - name: Run tests
        run: |
          source .env && docker-compose -f docker-compose.yml up --abort-on-container-exit e2e
